# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Event']] = 'Event'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EventActions[_PrismaModelT]':
        from .client import get_client

        return actions.EventActions[_PrismaModelT](client or get_client(), cls)


class BaseMarket(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Market']] = 'Market'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MarketActions[_PrismaModelT]':
        from .client import get_client

        return actions.MarketActions[_PrismaModelT](client or get_client(), cls)


class BaseMarketOutcome(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MarketOutcome']] = 'MarketOutcome'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MarketOutcomeActions[_PrismaModelT]':
        from .client import get_client

        return actions.MarketOutcomeActions[_PrismaModelT](client or get_client(), cls)


class BaseTag(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Tag']] = 'Tag'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TagActions[_PrismaModelT]':
        from .client import get_client

        return actions.TagActions[_PrismaModelT](client or get_client(), cls)


class BaseComment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Comment']] = 'Comment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CommentActions[_PrismaModelT]':
        from .client import get_client

        return actions.CommentActions[_PrismaModelT](client or get_client(), cls)


class BaseCommentReaction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CommentReaction']] = 'CommentReaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CommentReactionActions[_PrismaModelT]':
        from .client import get_client

        return actions.CommentReactionActions[_PrismaModelT](client or get_client(), cls)


class BaseUserProfile(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserProfile']] = 'UserProfile'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserProfileActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserProfileActions[_PrismaModelT](client or get_client(), cls)


class BaseCommentCheckpoint(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CommentCheckpoint']] = 'CommentCheckpoint'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CommentCheckpointActions[_PrismaModelT]':
        from .client import get_client

        return actions.CommentCheckpointActions[_PrismaModelT](client or get_client(), cls)


class BaseTokenPrice(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TokenPrice']] = 'TokenPrice'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TokenPriceActions[_PrismaModelT]':
        from .client import get_client

        return actions.TokenPriceActions[_PrismaModelT](client or get_client(), cls)


class BaseScraperRun(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ScraperRun']] = 'ScraperRun'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ScraperRunActions[_PrismaModelT]':
        from .client import get_client

        return actions.ScraperRunActions[_PrismaModelT](client or get_client(), cls)


