# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/opt/homebrew/lib/python3.10/site-packages/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/kostyalbalint/.cache/prisma-python/binaries/5.17.0/393aa359c9ad4a4bb28630fb5613f9c281cde053/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    event: 'actions.EventActions[models.Event]'
    market: 'actions.MarketActions[models.Market]'
    marketoutcome: 'actions.MarketOutcomeActions[models.MarketOutcome]'
    tag: 'actions.TagActions[models.Tag]'
    comment: 'actions.CommentActions[models.Comment]'
    commentreaction: 'actions.CommentReactionActions[models.CommentReaction]'
    userprofile: 'actions.UserProfileActions[models.UserProfile]'
    commentcheckpoint: 'actions.CommentCheckpointActions[models.CommentCheckpoint]'
    tokenprice: 'actions.TokenPriceActions[models.TokenPrice]'
    scraperrun: 'actions.ScraperRunActions[models.ScraperRun]'

    __slots__ = (
        'event',
        'market',
        'marketoutcome',
        'tag',
        'comment',
        'commentreaction',
        'userprofile',
        'commentcheckpoint',
        'tokenprice',
        'scraperrun',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.event = actions.EventActions[models.Event](self, models.Event)
        self.market = actions.MarketActions[models.Market](self, models.Market)
        self.marketoutcome = actions.MarketOutcomeActions[models.MarketOutcome](self, models.MarketOutcome)
        self.tag = actions.TagActions[models.Tag](self, models.Tag)
        self.comment = actions.CommentActions[models.Comment](self, models.Comment)
        self.commentreaction = actions.CommentReactionActions[models.CommentReaction](self, models.CommentReaction)
        self.userprofile = actions.UserProfileActions[models.UserProfile](self, models.UserProfile)
        self.commentcheckpoint = actions.CommentCheckpointActions[models.CommentCheckpoint](self, models.CommentCheckpoint)
        self.tokenprice = actions.TokenPriceActions[models.TokenPrice](self, models.TokenPrice)
        self.scraperrun = actions.ScraperRunActions[models.ScraperRun](self, models.ScraperRun)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/opt/homebrew/lib/python3.10/site-packages/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    event: 'EventBatchActions'
    market: 'MarketBatchActions'
    marketoutcome: 'MarketOutcomeBatchActions'
    tag: 'TagBatchActions'
    comment: 'CommentBatchActions'
    commentreaction: 'CommentReactionBatchActions'
    userprofile: 'UserProfileBatchActions'
    commentcheckpoint: 'CommentCheckpointBatchActions'
    tokenprice: 'TokenPriceBatchActions'
    scraperrun: 'ScraperRunBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.event = EventBatchActions(self)
        self.market = MarketBatchActions(self)
        self.marketoutcome = MarketOutcomeBatchActions(self)
        self.tag = TagBatchActions(self)
        self.comment = CommentBatchActions(self)
        self.commentreaction = CommentReactionBatchActions(self)
        self.userprofile = UserProfileBatchActions(self)
        self.commentcheckpoint = CommentCheckpointBatchActions(self)
        self.tokenprice = TokenPriceBatchActions(self)
        self.scraperrun = ScraperRunBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class EventBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.EventCreateInput,
        include: Optional[types.EventInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Event,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.EventCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Event,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.EventWhereUniqueInput,
        include: Optional[types.EventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Event,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.EventUpdateInput,
        where: types.EventWhereUniqueInput,
        include: Optional[types.EventInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Event,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.EventWhereUniqueInput,
        data: types.EventUpsertInput,
        include: Optional[types.EventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Event,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.EventUpdateManyMutationInput,
        where: types.EventWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Event,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.EventWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Event,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MarketBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MarketCreateInput,
        include: Optional[types.MarketInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Market,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MarketCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Market,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MarketWhereUniqueInput,
        include: Optional[types.MarketInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Market,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MarketUpdateInput,
        where: types.MarketWhereUniqueInput,
        include: Optional[types.MarketInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Market,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MarketWhereUniqueInput,
        data: types.MarketUpsertInput,
        include: Optional[types.MarketInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Market,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MarketUpdateManyMutationInput,
        where: types.MarketWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Market,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MarketWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Market,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MarketOutcomeBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MarketOutcomeCreateInput,
        include: Optional[types.MarketOutcomeInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.MarketOutcome,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MarketOutcomeCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.MarketOutcome,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MarketOutcomeWhereUniqueInput,
        include: Optional[types.MarketOutcomeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.MarketOutcome,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MarketOutcomeUpdateInput,
        where: types.MarketOutcomeWhereUniqueInput,
        include: Optional[types.MarketOutcomeInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.MarketOutcome,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MarketOutcomeWhereUniqueInput,
        data: types.MarketOutcomeUpsertInput,
        include: Optional[types.MarketOutcomeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.MarketOutcome,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MarketOutcomeUpdateManyMutationInput,
        where: types.MarketOutcomeWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.MarketOutcome,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MarketOutcomeWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.MarketOutcome,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TagBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TagCreateInput,
        include: Optional[types.TagInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Tag,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TagCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Tag,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TagWhereUniqueInput,
        include: Optional[types.TagInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Tag,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TagUpdateInput,
        where: types.TagWhereUniqueInput,
        include: Optional[types.TagInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Tag,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TagWhereUniqueInput,
        data: types.TagUpsertInput,
        include: Optional[types.TagInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Tag,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TagUpdateManyMutationInput,
        where: types.TagWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Tag,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TagWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Tag,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CommentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CommentCreateInput,
        include: Optional[types.CommentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Comment,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CommentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Comment,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CommentWhereUniqueInput,
        include: Optional[types.CommentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Comment,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CommentUpdateInput,
        where: types.CommentWhereUniqueInput,
        include: Optional[types.CommentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Comment,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CommentWhereUniqueInput,
        data: types.CommentUpsertInput,
        include: Optional[types.CommentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Comment,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CommentUpdateManyMutationInput,
        where: types.CommentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Comment,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CommentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Comment,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CommentReactionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CommentReactionCreateInput,
        include: Optional[types.CommentReactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CommentReaction,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CommentReactionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CommentReaction,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CommentReactionWhereUniqueInput,
        include: Optional[types.CommentReactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CommentReaction,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CommentReactionUpdateInput,
        where: types.CommentReactionWhereUniqueInput,
        include: Optional[types.CommentReactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CommentReaction,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CommentReactionWhereUniqueInput,
        data: types.CommentReactionUpsertInput,
        include: Optional[types.CommentReactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CommentReaction,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CommentReactionUpdateManyMutationInput,
        where: types.CommentReactionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CommentReaction,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CommentReactionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CommentReaction,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserProfileBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserProfileCreateInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserProfile,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserProfileCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserProfile,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserProfileUpdateInput,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserProfile,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserProfileWhereUniqueInput,
        data: types.UserProfileUpsertInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserProfileUpdateManyMutationInput,
        where: types.UserProfileWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserProfile,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserProfileWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserProfile,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CommentCheckpointBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CommentCheckpointCreateInput,
        include: Optional[types.CommentCheckpointInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CommentCheckpoint,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CommentCheckpointCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CommentCheckpoint,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CommentCheckpointWhereUniqueInput,
        include: Optional[types.CommentCheckpointInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CommentCheckpoint,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CommentCheckpointUpdateInput,
        where: types.CommentCheckpointWhereUniqueInput,
        include: Optional[types.CommentCheckpointInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CommentCheckpoint,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CommentCheckpointWhereUniqueInput,
        data: types.CommentCheckpointUpsertInput,
        include: Optional[types.CommentCheckpointInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CommentCheckpoint,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CommentCheckpointUpdateManyMutationInput,
        where: types.CommentCheckpointWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CommentCheckpoint,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CommentCheckpointWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CommentCheckpoint,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TokenPriceBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TokenPriceCreateInput,
        include: Optional[types.TokenPriceInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.TokenPrice,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TokenPriceCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.TokenPrice,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TokenPriceWhereUniqueInput,
        include: Optional[types.TokenPriceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.TokenPrice,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TokenPriceUpdateInput,
        where: types.TokenPriceWhereUniqueInput,
        include: Optional[types.TokenPriceInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.TokenPrice,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TokenPriceWhereUniqueInput,
        data: types.TokenPriceUpsertInput,
        include: Optional[types.TokenPriceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.TokenPrice,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TokenPriceUpdateManyMutationInput,
        where: types.TokenPriceWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.TokenPrice,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TokenPriceWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.TokenPrice,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ScraperRunBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ScraperRunCreateInput,
        include: Optional[types.ScraperRunInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ScraperRun,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ScraperRunCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ScraperRun,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ScraperRunWhereUniqueInput,
        include: Optional[types.ScraperRunInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ScraperRun,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ScraperRunUpdateInput,
        where: types.ScraperRunWhereUniqueInput,
        include: Optional[types.ScraperRunInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ScraperRun,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ScraperRunWhereUniqueInput,
        data: types.ScraperRunUpsertInput,
        include: Optional[types.ScraperRunInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ScraperRun,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ScraperRunUpdateManyMutationInput,
        where: types.ScraperRunWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ScraperRun,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ScraperRunWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ScraperRun,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma