from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Event',
    'Market',
    'MarketOutcome',
    'Tag',
    'Comment',
    'CommentReaction',
    'UserProfile',
    'CommentCheckpoint',
    'TokenPrice',
    'ScraperRun',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Event': {
        'markets': 'Market',
        'tags': 'Tag',
        'Comment': 'Comment',
        'CommentCheckpoint': 'CommentCheckpoint',
    },
    'Market': {
        'events': 'Event',
        'tags': 'Tag',
        'marketOutcomes': 'MarketOutcome',
    },
    'MarketOutcome': {
        'market': 'Market',
        'priceSnapshots': 'TokenPrice',
    },
    'Tag': {
        'markets': 'Market',
        'Event': 'Event',
    },
    'Comment': {
        'profile': 'UserProfile',
        'event': 'Event',
        'parentComment': 'Comment',
        'childComments': 'Comment',
        'reactions': 'CommentReaction',
    },
    'CommentReaction': {
        'comment': 'Comment',
    },
    'UserProfile': {
        'Comment': 'Comment',
    },
    'CommentCheckpoint': {
        'event': 'Event',
    },
    'TokenPrice': {
        'marketOutcome': 'MarketOutcome',
    },
    'ScraperRun': {
    },
}

# fmt: on